<?php
/**
 * ProductOfferDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Emesa\PartnerPlatform
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Supplier API
 *
 * Supplier API description... <br /><br /> Open [OpenAPI.json](doc.json).
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Emesa\PartnerPlatform\Model;

use \ArrayAccess;
use \Emesa\PartnerPlatform\ObjectSerializer;

/**
 * ProductOfferDto Class Doc Comment
 *
 * @category Class
 * @package  Emesa\PartnerPlatform
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductOfferDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ProductOfferDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'stock' => 'int',
'target_price_in_cents' => 'int',
'market_shipping_class_id' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'stock' => null,
'target_price_in_cents' => null,
'market_shipping_class_id' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'stock' => 'stock',
'target_price_in_cents' => 'targetPriceInCents',
'market_shipping_class_id' => 'marketShippingClassId'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'stock' => 'setStock',
'target_price_in_cents' => 'setTargetPriceInCents',
'market_shipping_class_id' => 'setMarketShippingClassId'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'stock' => 'getStock',
'target_price_in_cents' => 'getTargetPriceInCents',
'market_shipping_class_id' => 'getMarketShippingClassId'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const MARKET_SHIPPING_CLASS_ID_S = 'S';
const MARKET_SHIPPING_CLASS_ID_M = 'M';
const MARKET_SHIPPING_CLASS_ID_XL = 'XL';
const MARKET_SHIPPING_CLASS_ID_SPEC_1 = 'SPEC_1';
const MARKET_SHIPPING_CLASS_ID_SPEC_2 = 'SPEC_2';
const MARKET_SHIPPING_CLASS_ID_SPEC_3 = 'SPEC_3';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getMarketShippingClassIdAllowableValues()
    {
        return [
            self::MARKET_SHIPPING_CLASS_ID_S,
self::MARKET_SHIPPING_CLASS_ID_M,
self::MARKET_SHIPPING_CLASS_ID_XL,
self::MARKET_SHIPPING_CLASS_ID_SPEC_1,
self::MARKET_SHIPPING_CLASS_ID_SPEC_2,
self::MARKET_SHIPPING_CLASS_ID_SPEC_3,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['stock'] = isset($data['stock']) ? $data['stock'] : null;
        $this->container['target_price_in_cents'] = isset($data['target_price_in_cents']) ? $data['target_price_in_cents'] : null;
        $this->container['market_shipping_class_id'] = isset($data['market_shipping_class_id']) ? $data['market_shipping_class_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['stock'] === null) {
            $invalidProperties[] = "'stock' can't be null";
        }
        if ($this->container['target_price_in_cents'] === null) {
            $invalidProperties[] = "'target_price_in_cents' can't be null";
        }
        if ($this->container['market_shipping_class_id'] === null) {
            $invalidProperties[] = "'market_shipping_class_id' can't be null";
        }
        $allowedValues = $this->getMarketShippingClassIdAllowableValues();
        if (!is_null($this->container['market_shipping_class_id']) && !in_array($this->container['market_shipping_class_id'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'market_shipping_class_id', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets stock
     *
     * @return int
     */
    public function getStock()
    {
        return $this->container['stock'];
    }

    /**
     * Sets stock
     *
     * @param int $stock stock
     *
     * @return $this
     */
    public function setStock($stock)
    {
        $this->container['stock'] = $stock;

        return $this;
    }

    /**
     * Gets target_price_in_cents
     *
     * @return int
     */
    public function getTargetPriceInCents()
    {
        return $this->container['target_price_in_cents'];
    }

    /**
     * Sets target_price_in_cents
     *
     * @param int $target_price_in_cents target_price_in_cents
     *
     * @return $this
     */
    public function setTargetPriceInCents($target_price_in_cents)
    {
        $this->container['target_price_in_cents'] = $target_price_in_cents;

        return $this;
    }

    /**
     * Gets market_shipping_class_id
     *
     * @return string
     */
    public function getMarketShippingClassId()
    {
        return $this->container['market_shipping_class_id'];
    }

    /**
     * Sets market_shipping_class_id
     *
     * @param string $market_shipping_class_id market_shipping_class_id
     *
     * @return $this
     */
    public function setMarketShippingClassId($market_shipping_class_id)
    {
        $allowedValues = $this->getMarketShippingClassIdAllowableValues();
        if (!in_array($market_shipping_class_id, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'market_shipping_class_id', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['market_shipping_class_id'] = $market_shipping_class_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
