<?php
/**
 * ProductContentDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Emesa\PartnerPlatform
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Supplier API
 *
 * Supplier API description... <br /><br /> Open [OpenAPI.json](doc.json).
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Emesa\PartnerPlatform;

/**
 * ProductContentDtoTest Class Doc Comment
 *
 * @category    Class
 * @description ProductContentDto
 * @package     Emesa\PartnerPlatform
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductContentDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductContentDto"
     */
    public function testProductContentDto()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "short_description"
     */
    public function testPropertyShortDescription()
    {
    }

    /**
     * Test attribute "seo_description"
     */
    public function testPropertySeoDescription()
    {
    }

    /**
     * Test attribute "extra_description"
     */
    public function testPropertyExtraDescription()
    {
    }

    /**
     * Test attribute "main_usp"
     */
    public function testPropertyMainUsp()
    {
    }

    /**
     * Test attribute "full_specifications"
     */
    public function testPropertyFullSpecifications()
    {
    }
}
