<?php
/**
 * ProductsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Emesa\PartnerPlatform
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Supplier API
 *
 * Supplier API description... <br /><br /> Open [OpenAPI.json](doc.json).
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.29
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Emesa\PartnerPlatform;

use Emesa\PartnerPlatform\Configuration;
use Emesa\PartnerPlatform\ApiException;
use Emesa\PartnerPlatform\ObjectSerializer;

/**
 * ProductsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Emesa\PartnerPlatform
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getOffer
     *
     * .
     *
     */
    public function testGetOffer()
    {
    }

    /**
     * Test case for getProduct
     *
     * .
     *
     */
    public function testGetProduct()
    {
    }

    /**
     * Test case for listProducts
     *
     * .
     *
     */
    public function testListProducts()
    {
    }

    /**
     * Test case for putOffer
     *
     * .
     *
     */
    public function testPutOffer()
    {
    }

    /**
     * Test case for putProduct
     *
     * .
     *
     */
    public function testPutProduct()
    {
    }
}
